name: flutter_app_test_stacked
description: An app build with the stacked framework

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  stacked: ^3.2.0
  stacked_services: ^1.0.0
  http: ^0.13.5
  intl: ^0.18.1
  flutter_svg: ^2.0.5
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.2.0
  stacked_generator: ^1.0.0
  mockito: ^5.3.2
  collection: ^1.16.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mulish/Mulish-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/Mulish/Mulish-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Mulish/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/Mulish-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/Mulish-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/Mulish-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Mulish/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/Mulish/Mulish-BlackItalic.ttf
          weight: 900
          style: italic

